#!/usr/bin/env bash
set -euo pipefail
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" --set=api_password="$ATMS_APP_PASSWORD" <<'SQL'
CREATE ROLE atms_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE PASSWORD :'api_password';
GRANT CONNECT ON DATABASE atms TO atms_app;
GRANT USAGE ON SCHEMA public TO atms_app;
ALTER DEFAULT PRIVILEGES FOR ROLE atms IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO atms_app;
ALTER DEFAULT PRIVILEGES FOR ROLE atms IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO atms_app;
SQL
