// @vitest-environment jsdom
// [F04 K1~K6] 실제 React/Query/요청 함수를 DOM에 올린다. fetch 경계만 가상 HTTP로 대체한다.
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import Accounts from '../src/pages/accounting/Accounts'
import AccountForm from '../src/components/accounts/AccountForm'
import AccountDetail from '../src/components/accounts/AccountDetail'
import { accountApi, type AccountView, type CompanyRole } from '../src/lib/api'

const auth = vi.hoisted(() => ({ expire: vi.fn() }))
vi.mock('../src/context/AuthContext', () => ({ useAuth: () => ({ session: { user: { id: 'test-user' }, csrfToken: 'test-csrf' }, expire: auth.expire }) }))
const a = '10000000-0000-4000-8000-000000000001', b = '10000000-0000-4000-8000-000000000002'
const uid = (n: number) => `50000000-0000-4000-8000-${String(n).padStart(12, '0')}`
const makeRow = (n = 1, patch: Partial<AccountView> = {}): AccountView => ({ id: uid(n), code: `CODE${n}`, name: `계정 ${n}`, category: 'ASSET', normalBalance: 'DEBIT', active: true, version: 1, canUseInJournal: true, ...patch })
const companies = [a, b].map((id, i) => ({ id, name: `시험 회사 ${i ? 'B' : 'A'}`, currency: 'KRW', accountingStandard: 'KGAAP', allowSelfApproval: false, version: 1 }))
type Call = { url: URL; method: string; init: RequestInit; body: Record<string, unknown> }
let calls: Call[], data: AccountView[], role: CompanyRole, noCompanies: boolean, companyNext: boolean
let override: ((call: Call) => Response | Promise<Response> | undefined) | undefined
let clients: QueryClient[]
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json' } })
const error = (status: number) => json({ code: 'TEST_ERROR' }, status)
const writes = () => calls.filter(c => c.url.pathname.includes('/accounts') && c.method !== 'GET')
const listCalls = () => calls.filter(c => c.method === 'GET' && c.url.pathname.endsWith('/accounts'))
// [수리 K8] RTL의 문자열 name은 정확한 접근 가능한 이름으로 찾는다. Playwright의 exact 옵션을 섞지 않는다.
const button = (name: string) => screen.getAllByRole('button', { name })[0]
const change = (label: string, value: string) => fireEvent.change(screen.getByLabelText(label), { target: { value } })
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(done => { resolve = done }); return { promise, resolve } }
function mount() {
    const cache = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: 30_000, refetchOnWindowFocus: false, gcTime: Infinity } } }); clients.push(cache)
    const view = render(<QueryClientProvider client={cache}><Accounts /></QueryClientProvider>); return { ...view, cache }
}
async function select(id = a) { await screen.findByLabelText('관리할 회사'); change('관리할 회사', id); await screen.findByRole('heading', { name: '계정과목 목록' }); await waitFor(() => expect(screen.queryByText('계정과목 목록 갱신 중…')).toBeNull()) }
async function detail(n = 1) { fireEvent.click(button(`CODE${n} · 계정 ${n} 상세`)); await screen.findByRole('heading', { name: `계정 ${n}` }); await waitFor(() => expect(screen.queryByText('계정 상세를 불러오는 중입니다…')).toBeNull()) }
function fill(name = '새 계정') { change('계정 코드', ' abc_1 '); change('계정 이름', ` ${name} `); change('계정 분류', 'ASSET'); change('정상 잔액 방향', 'CREDIT') }
async function createForm() { fireEvent.click(button('새 계정 등록')); await screen.findByLabelText('계정 코드'); fill() }

beforeEach(() => {
    vi.clearAllMocks(); calls = []; data = [makeRow()]; role = 'COMPANY_ADMIN'; noCompanies = false; companyNext = false; override = undefined; clients = []
    window.localStorage.clear(); window.sessionStorage.clear()
    vi.stubGlobal('requestAnimationFrame', (fn: FrameRequestCallback) => setTimeout(() => fn(0), 0))
    vi.stubGlobal('fetch', vi.fn(async (path: string, init: RequestInit = {}) => {
        const call: Call = { url: new URL(path, 'https://example.invalid'), method: init.method ?? 'GET', init, body: init.body ? JSON.parse(String(init.body)) : {} }; calls.push(call)
        const custom = override?.(call); if (custom !== undefined) return await custom
        if (call.url.pathname === '/api/companies') return json({ items: noCompanies ? [] : companyNext && !call.url.searchParams.has('cursor') ? companies.slice(0, 1) : companies, nextCursor: companyNext && !call.url.searchParams.has('cursor') ? a : null })
        if (call.url.pathname.endsWith('/select')) return json({ company: companies.find(c => call.url.pathname.includes(c.id)), roles: [role], permissions: ['accounts.read', ...(role === 'COMPANY_ADMIN' ? ['accounts.manage'] : [])] })
        if (call.url.pathname.endsWith('/accounts') && call.method === 'GET') {
            const q = call.url.searchParams.get('q')?.toLowerCase(), cat = call.url.searchParams.get('category'), active = call.url.searchParams.get('active'), cursor = call.url.searchParams.get('cursor')
            const items = data.filter(row => (!q || `${row.code} ${row.name}`.toLowerCase().includes(q)) && (!cat || row.category === cat) && (active === 'all' || row.active === (active === 'active')) && (!cursor || row.id > cursor)).slice(0, 20)
            return json({ items, nextCursor: items.length === 20 && data.some(r => r.id > items[19].id) ? items[19].id : null })
        }
        if (call.url.pathname.endsWith('/accounts') && call.method === 'POST') { const row = makeRow(90, call.body as Partial<AccountView>); data.push(row); return json(row) }
        const id = call.url.pathname.split('/')[5], row = data.find(r => r.id === id)
        if (!row) return error(404)
        if (call.method !== 'GET') { if (call.body.version !== row.version) return error(409); Object.assign(row, call.url.pathname.endsWith('/deactivate') ? { active: false, canUseInJournal: false } : call.body, { version: row.version + 1 }) }
        return json(row)
    }))
})
afterEach(() => { cleanup(); clients.forEach(c => c.clear()); vi.restoreAllMocks(); vi.unstubAllGlobals() })

describe('K1 company scope and roles', () => {
    it('requires explicit company selection and does not request accounts before it', async () => { mount(); await screen.findByLabelText('관리할 회사'); expect(listCalls()).toHaveLength(0); expect((screen.getByLabelText('관리할 회사') as HTMLSelectElement).value).toBe('') })
    it.each(['COMPANY_ADMIN', 'ACCOUNTANT', 'APPROVER', 'READ_ONLY', 'EXTERNAL_TAX'] as CompanyRole[])('uses current permissions for %s', async selectedRole => { role = selectedRole; mount(); await select(); await detail(); expect(screen.queryByRole('button', { name: '새 계정 등록' }) !== null).toBe(role === 'COMPANY_ADMIN'); expect(screen.queryByRole('button', { name: '계정 수정' }) !== null).toBe(role === 'COMPANY_ADMIN') })
    it('shows empty accessible-company state', async () => { noCompanies = true; mount(); await screen.findByRole('heading', { name: '접근 가능한 회사가 없습니다' }); expect(listCalls()).toHaveLength(0) })
    it('loads another company page explicitly', async () => { companyNext = true; mount(); await screen.findByLabelText('관리할 회사'); fireEvent.click(button('회사 더 불러오기')); await screen.findByRole('option', { name: '시험 회사 B' }); expect(calls.some(c => c.url.searchParams.get('cursor') === a)).toBe(true) })
    it('ignores late company selection and clears previous company detail', async () => { const old = deferred<Response>(); override = c => c.url.pathname === `/api/companies/${a}/select` ? old.promise : undefined; mount(); await screen.findByLabelText('관리할 회사'); change('관리할 회사', a); change('관리할 회사', b); await screen.findByRole('heading', { name: '계정과목 목록' }); await act(async () => old.resolve(json({ company: companies[0], roles: ['COMPANY_ADMIN'], permissions: ['accounts.read', 'accounts.manage'] }))); expect((screen.getByLabelText('관리할 회사') as HTMLSelectElement).value).toBe(b); expect(listCalls().every(c => c.url.pathname.includes(b))).toBe(true) })
    it('aborts a previous list on company change and does not reveal its late rows', async () => { const pending = deferred<Response>(); override = c => c.url.pathname === `/api/companies/${a}/accounts` ? pending.promise : undefined; mount(); await screen.findByLabelText('관리할 회사'); change('관리할 회사', a); await waitFor(() => expect(listCalls()).toHaveLength(1)); const signal = listCalls()[0].init.signal; change('관리할 회사', b); await screen.findByRole('heading', { name: '계정과목 목록' }); await waitFor(() => expect(signal?.aborted).toBe(true)); await act(async () => pending.resolve(json({ items: [makeRow(80, { name: '이전 회사 비공개' })], nextCursor: null }))); expect(screen.queryByText(/이전 회사 비공개/)).toBeNull() })
})

describe('K2 server queries and paging', () => {
    it('sends normalized search, category, state and limit20 to the server', async () => { mount(); await select(); change('계정 검색', ' CODE1 '); fireEvent.click(button('검색')); await waitFor(() => expect(listCalls().at(-1)?.url.searchParams.get('q')).toBe('CODE1')); change('분류 필터', 'ASSET'); change('사용 상태', 'all'); await waitFor(() => expect(listCalls().at(-1)?.url.searchParams.get('active')).toBe('all')); const q = listCalls().at(-1)!.url.searchParams; expect(q.get('category')).toBe('ASSET'); expect(q.get('limit')).toBe('20') })
    // [수리 K2] 최신 캐시가 있는 이전 페이지는 새 GET 없이 복원된다. 실제 행/페이지/선택 초기화를 검증한다.
    it('moves next by cursor and restores the cached previous page without old selection', async () => { data = Array.from({ length: 21 }, (_, i) => makeRow(i + 1)); mount(); await select(); await detail(); fireEvent.click(button('다음 페이지')); await screen.findByText('2페이지'); await screen.findAllByRole('button', { name: 'CODE21 · 계정 21 상세' }); expect(listCalls().at(-1)?.url.searchParams.get('cursor')).toBe(uid(20)); expect(screen.queryByRole('heading', { name: '계정 1' })).toBeNull(); const requests = listCalls().length; fireEvent.click(button('이전 페이지')); await screen.findByText('1페이지'); await screen.findAllByRole('button', { name: 'CODE1 · 계정 1 상세' }); expect(screen.queryAllByRole('button', { name: 'CODE21 · 계정 21 상세' })).toHaveLength(0); expect(listCalls()).toHaveLength(requests); expect(screen.queryByRole('heading', { name: '계정 1' })).toBeNull() })
    it('shows registered-empty and filtered-zero states only after success', async () => { data = []; mount(); await select(); await screen.findByText('등록된 사용중 계정이 없습니다.'); change('계정 검색', '없음'); fireEvent.click(button('검색')); await screen.findByText('검색 조건과 일치하는 계정이 없습니다.') })
    it('rejects overlong search without another API call', async () => { mount(); await select(); const n = listCalls().length; change('계정 검색', '가'.repeat(101)); fireEvent.click(button('검색')); await screen.findByText('검색어는 올바른 문자로 100자 이내에 입력해 주세요.'); expect(listCalls()).toHaveLength(n) })
})

describe('K3 form contract', () => {
    it.each(['', 'a'.repeat(21), 'ß', '가', 'a b'])('rejects invalid ASCII code %s', code => { const submit = vi.fn(); render(<AccountForm locked={false} onDirty={vi.fn()} onSubmit={submit} onCancel={vi.fn()} />); fill(); change('계정 코드', code); fireEvent.click(button('계정 등록')); expect(submit).not.toHaveBeenCalled(); expect(screen.getByLabelText('계정 코드').getAttribute('aria-invalid')).toBe('true') })
    it.each(['', '가'.repeat(101), '\0', '\ud800'])('rejects invalid name boundary', name => { const submit = vi.fn(); render(<AccountForm locked={false} onDirty={vi.fn()} onSubmit={submit} onCancel={vi.fn()} />); fill(); change('계정 이름', name); fireEvent.click(button('계정 등록')); expect(submit).not.toHaveBeenCalled() })
    it('accepts 100 Unicode code points and explicit contra direction', () => { const submit = vi.fn(); render(<AccountForm locked={false} onDirty={vi.fn()} onSubmit={submit} onCancel={vi.fn()} />); fill('😀'.repeat(100)); fireEvent.click(button('계정 등록')); expect(submit).toHaveBeenCalledWith({ code: 'ABC_1', name: '😀'.repeat(100), category: 'ASSET', normalBalance: 'CREDIT' }) })
    it('starts classification and direction empty, focuses linked error summary', async () => { render(<AccountForm locked={false} onDirty={vi.fn()} onSubmit={vi.fn()} onCancel={vi.fn()} />); expect((screen.getByLabelText('계정 분류') as HTMLSelectElement).value).toBe(''); expect((screen.getByLabelText('정상 잔액 방향') as HTMLSelectElement).value).toBe(''); fireEvent.click(button('계정 등록')); await waitFor(() => expect(document.activeElement?.getAttribute('role')).toBe('alert')); expect(screen.getByRole('link', { name: '분류를 선택해 주세요.' }).getAttribute('href')).toBe('#account-category') })
    it('keeps classified code/category/direction immutable and sends only name/version', async () => { mount(); await select(); await detail(); fireEvent.click(button('계정 수정')); expect((screen.getByLabelText('계정 코드') as HTMLInputElement).readOnly).toBe(true); expect((screen.getByLabelText('계정 분류') as HTMLSelectElement).disabled).toBe(true); change('계정 이름', '새 이름'); fireEvent.click(button('변경 저장')); await screen.findByRole('heading', { name: '새 이름' }); expect(writes()[0].body).toEqual({ version: 1, name: '새 이름' }) })
    it('classifies a legacy account by sending both fields once', async () => { data = [makeRow(1, { category: null, normalBalance: null, canUseInJournal: false })]; mount(); await select(); await detail(); expect(screen.getByText('자격 없음')).toBeTruthy(); fireEvent.click(button('계정 수정')); change('계정 분류', 'ASSET'); change('정상 잔액 방향', 'CREDIT'); fireEvent.click(button('변경 저장')); await waitFor(() => expect(writes()).toHaveLength(1)); expect(writes()[0].body).toEqual({ version: 1, category: 'ASSET', normalBalance: 'CREDIT' }) })
    it('does not write unchanged classified input', async () => { mount(); await select(); await detail(); fireEvent.click(button('계정 수정')); fireEvent.click(button('변경 저장')); await screen.findByText('변경된 값이 없습니다.'); expect(writes()).toHaveLength(0) })
    it('does not offer edit/deactivate/reactivation on an inactive account', () => { render(<AccountDetail row={makeRow(1, { active: false, canUseInJournal: false })} canWrite busy={false} onEdit={vi.fn()} onDeactivate={vi.fn()} />); expect(screen.queryByRole('button')).toBeNull(); expect(screen.getByText('자격 없음')).toBeTruthy() })
})

describe('K4 fixed create request and recovery', () => {
    // [수리 K4] 기존 requestJson의 쿠키/JSON/CSRF 계약을 확인한다. 서버 응답 캐시 정책을 fetch 옵션으로 가정하지 않는다.
    it('locks navigation and blocks synchronous double submit, preserving normalized JSON and CSRF', async () => { const pending = deferred<Response>(); override = c => c.method === 'POST' && c.url.pathname.endsWith('/accounts') ? pending.promise : undefined; mount(); await select(); await createForm(); const submit = button('계정 등록'); fireEvent.click(submit); fireEvent.click(submit); expect(writes()).toHaveLength(1); expect((screen.getByLabelText('관리할 회사') as HTMLSelectElement).disabled).toBe(true); expect(writes()[0].body).toMatchObject({ code: 'ABC_1', name: '새 계정', category: 'ASSET', normalBalance: 'CREDIT' }); expect(writes()[0].body.creationRequestId).toMatch(/^[0-9a-f-]{36}$/); expect(writes()[0].init.credentials).toBe('include'); expect(writes()[0].init.headers).toMatchObject({ 'X-CSRF-Token': 'test-csrf', 'Content-Type': 'application/json' }); await act(async () => pending.resolve(json(makeRow(90, { code: 'ABC_1', name: '새 계정' })))); await screen.findByRole('heading', { name: '새 계정' }) })
    it.each(['network', '503'])('retries %s only with the exact same UUID/body after explicit click', async failure => { let n = 0; override = c => { if (c.method === 'POST' && c.url.pathname.endsWith('/accounts') && n++ === 0) { if (failure === 'network') return Promise.reject(new TypeError('offline')); return error(503) } }; mount(); await select(); await createForm(); fireEvent.click(button('계정 등록')); await screen.findByRole('button', { name: '같은 요청으로 재시도' }); expect(writes()).toHaveLength(1); expect((screen.getByLabelText('계정 이름') as HTMLInputElement).disabled).toBe(true); fireEvent.click(button('같은 요청으로 재시도')); await screen.findByRole('heading', { name: '새 계정' }); expect(writes()).toHaveLength(2); expect(writes()[1].body).toEqual(writes()[0].body); expect(window.localStorage.length + window.sessionStorage.length).toBe(0) })
    it('requires inline confirmation before discarding a dirty draft/company switch', async () => { mount(); await select(); await createForm(); change('관리할 회사', b); expect((screen.getByLabelText('관리할 회사') as HTMLSelectElement).value).toBe(a); fireEvent.click(button('계속 입력')); expect(screen.getByLabelText('계정 이름')).toBeTruthy(); change('관리할 회사', b); fireEvent.click(button('입력 폐기 확인')); await waitFor(() => expect((screen.getByLabelText('관리할 회사') as HTMLSelectElement).value).toBe(b)); expect(screen.queryByLabelText('계정 이름')).toBeNull(); expect(writes()).toHaveLength(0) })
})

describe('K5 version and deactivate', () => {
    it('requires inline deactivate confirmation and sends the displayed version', async () => { mount(); await select(); await detail(); fireEvent.click(button('사용 중지')); expect(writes()).toHaveLength(0); fireEvent.click(button('중지 취소')); expect(writes()).toHaveLength(0); fireEvent.click(button('사용 중지')); fireEvent.click(button('사용 중지 확인')); await screen.findByText(/중지된 계정입니다/); expect(writes()[0].body).toEqual({ version: 1 }); expect(writes()[0].url.pathname.endsWith('/deactivate')).toBe(true); expect(data[0].active).toBe(false) })
    it.each([409, 503, 'network'] as const)('discards ambiguous/stale edit for %s, refetches and never overwrites automatically', async status => { override = c => c.method === 'PATCH' ? status === 'network' ? Promise.reject(new TypeError('offline')) : error(status) : undefined; mount(); await select(); await detail(); fireEvent.click(button('계정 수정')); change('계정 이름', '초안'); fireEvent.click(button('변경 저장')); await screen.findByText('이전 입력을 폐기했습니다. 최신 상세를 확인하고 다시 입력해 주세요.'); await screen.findByRole('heading', { name: '계정 1' }); expect(writes()).toHaveLength(1); expect(screen.queryByLabelText('계정 이름')).toBeNull(); expect(calls.filter(c => c.method === 'GET' && c.url.pathname.endsWith(uid(1))).length).toBeGreaterThanOrEqual(2) })
    it('clears a deleted detail after update404 and refreshes list', async () => { override = c => c.method === 'PATCH' ? error(404) : undefined; mount(); await select(); await detail(); fireEvent.click(button('계정 수정')); change('계정 이름', '초안'); fireEvent.click(button('변경 저장')); await screen.findByText('계정을 찾지 못했습니다. 목록을 다시 확인해 주세요.'); await waitFor(() => expect(screen.queryByRole('heading', { name: '계정 1' })).toBeNull()); expect(listCalls().length).toBeGreaterThan(1) })
})

describe('K6 safe errors and unmount', () => {
    it.each([400, 404, 409, 429, 503, 'network'] as const)('shows read failure %s without empty-success or automatic retry', async status => { override = c => c.url.pathname.endsWith('/accounts') ? status === 'network' ? Promise.reject(new TypeError('offline')) : error(status) : undefined; mount(); await select(); await screen.findByRole('heading', { name: '계정 목록을 불러오지 못했습니다' }); expect(screen.queryByText('등록된 사용중 계정이 없습니다.')).toBeNull(); expect(listCalls()).toHaveLength(1); fireEvent.click(button('다시 시도')); await waitFor(() => expect(listCalls()).toHaveLength(2)) })
    it('expires401 through the auth context', async () => { override = c => c.url.pathname.endsWith('/accounts') ? error(401) : undefined; mount(); await select(); await waitFor(() => expect(auth.expire).toHaveBeenCalled()) })
    it('rechecks403 and removes data/cache when company access is lost', async () => { let selects = 0; override = c => { if (c.url.pathname.endsWith('/select') && ++selects > 1) return error(403); if (c.url.pathname.endsWith('/accounts')) return error(403) }; const view = mount(); await select(); await screen.findByText('회사 접근 권한을 확인하지 못했습니다. 회사를 다시 선택해 주세요.'); expect((screen.getByLabelText('관리할 회사') as HTMLSelectElement).value).toBe(''); expect(view.cache.getQueriesData({ queryKey: ['accounts', 'test-user', a] })).toHaveLength(0); expect(writes()).toHaveLength(0) })
    it('removes draft and manage controls after write403 with read-only membership', async () => { override = c => { if (c.method === 'POST' && c.url.pathname.endsWith('/accounts')) { role = 'READ_ONLY'; return error(403) } }; mount(); await select(); await createForm(); fireEvent.click(button('계정 등록')); await screen.findByText('현재 회사 권한을 다시 확인했습니다.'); expect(screen.queryByLabelText('계정 이름')).toBeNull(); expect(screen.queryByRole('button', { name: '새 계정 등록' })).toBeNull() })
    it('aborts reads on unmount even if response ignores abort', async () => { const pending = deferred<Response>(); override = c => c.url.pathname.endsWith('/accounts') ? pending.promise : undefined; const view = mount(); await screen.findByLabelText('관리할 회사'); change('관리할 회사', a); await waitFor(() => expect(listCalls()).toHaveLength(1)); const signal = listCalls()[0].init.signal; view.unmount(); expect(signal?.aborted).toBe(true); await act(async () => pending.resolve(json({ items: [makeRow()], nextCursor: null }))); expect(writes()).toHaveLength(0) })
    it('ignores a pending create result after leaving the page', async () => { const pending = deferred<Response>(); override = c => c.method === 'POST' && c.url.pathname.endsWith('/accounts') ? pending.promise : undefined; const view = mount(); await select(); await createForm(); fireEvent.click(button('계정 등록')); view.unmount(); await act(async () => pending.resolve(json(makeRow(90)))); expect(view.cache.getQueryData(['account', 'test-user', a, uid(90)])).toBeUndefined(); expect(writes()).toHaveLength(1) })
    it('does not expose internal error details containing submitted values', async () => { override = c => c.method === 'POST' && c.url.pathname.endsWith('/accounts') ? json({ code: 'SECRET_INTERNAL', details: [{ message: 'private hash abc' }] }, 409) : undefined; mount(); await select(); await createForm(); fireEvent.click(button('계정 등록')); await screen.findByText(/코드, 요청 또는 버전이 충돌/); expect(screen.queryByText(/private hash/)).toBeNull() })
    it('API list and detail GET forward their AbortSignal without CSRF or mutations', async () => { const c = new AbortController(); await accountApi.list(a, { active: 'all' }, uid(1), c.signal); await accountApi.detail(a, uid(1), c.signal); expect(calls.every(call => call.init.signal === c.signal && call.method === 'GET')).toBe(true); expect(calls[0].init.headers).not.toHaveProperty('X-CSRF-Token') })
})
