// @vitest-environment jsdom
// [K1~K6] 실제 Auth/Query/Router와 화면을 사용한다. HTTP 경계만 대체하며 저장 본문·재시도·표시를 관찰한다.
import { act, cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { MemoryRouter } from 'react-router-dom'
import { AuthProvider, useAuth } from '../src/context/AuthContext'
import Journals from '../src/pages/accounting/Journals'
import Evidence from '../src/pages/accounting/Evidence'
import EvidenceDetail from '../src/components/evidence/EvidenceDetail'
import JournalReferencePicker from '../src/components/journals/JournalReferencePicker'
import { companyApi, journalApi, type CompanyRole, type EvidenceView, type JournalDetailView } from '../src/lib/api'
import { draftValues, journalTotals, normalizeJournalDraft, won, validDate, validText, type JournalDraftValues } from '../src/lib/journalDraftForm'

const id = (n: number) => `50000000-0000-4000-8000-${String(n).padStart(12, '0')}`
const a = id(1), b = id(2), fy = id(3), ea = id(4), aa = id(5), ab = id(6), user = id(7)
const years = [{ id: fy, startDate: '2026-01-01', endDate: '2026-12-31' }]
const companies = [a, b].map((company, i) => ({ id: company, name: `시험 회사 ${i ? 'B' : 'A'}`, currency: 'KRW', accountingStandard: 'KGAAP', allowSelfApproval: false, version: 1 }))
const accounts = [aa, ab].map((account, i) => ({ id: account, code: `A${i}`, name: `시험 계정 ${i}`, active: true, category: i ? 'LIABILITY' : 'EXPENSE', normalBalance: i ? 'CREDIT' : 'DEBIT', canUseInJournal: true, version: 1 }))
const evidence: EvidenceView = { id: ea, companyId: a, title: '시험 PDF', kind: 'OTHER', occurredOn: null, counterpartyId: null, originalFileName: 'test.pdf', mediaType: 'application/pdf', byteSize: 100, createdById: user, createdAt: '2026-10-07T00:00:00Z' }
const row = (n = 20): JournalDetailView => ({ id: id(n), number: `2026-${n}`, fiscalYearId: fy, accountingDate: '2026-10-07', memo: '저장 초안', currency: 'KRW', status: 'DRAFT', version: 1, debitTotal: '9007199254740993', creditTotal: '9007199254740993', lineCount: 2, evidenceCount: 1, createdById: user, counterpartyId: null, evidenceIds: [ea], createdAt: '2026-10-07T00:00:00Z', updatedAt: '2026-10-07T00:00:00Z', lines: [aa, ab].map((accountId, i) => ({ id: id(30 + i), position: i + 1, accountId, debit: i ? '0' : '9007199254740993', credit: i ? '9007199254740993' : '0', memo: null })) })
function valid(): JournalDraftValues { return { ...draftValues(row()), memo: ' 새 적요 ', lines: row().lines.map(l => ({ accountId: l.accountId, debit: l.debit, credit: l.credit, memo: '' })) } }
type Call = { url: URL; method: string; init: RequestInit; body: Record<string, any> }
let calls: Call[], data: JournalDetailView[], role: CompanyRole, noCompanies: boolean, next: boolean, clients: QueryClient[]
let override: ((call: Call) => Response | Promise<Response> | undefined) | undefined
const json = (value: unknown, status = 200) => new Response(JSON.stringify(value), { status, headers: { 'Content-Type': 'application/json' } })
const error = (status: number) => json({ code: 'TEST_ERROR', details: [{ message: 'private internal' }] }, status)
const writes = () => calls.filter(c => c.url.pathname.includes('/journals') && c.method !== 'GET')
const listCalls = () => calls.filter(c => c.method === 'GET' && c.url.pathname === `/api/companies/${a}/journals`)
const button = (name: string) => screen.getAllByRole('button', { name })[0]
const change = (label: string, value: string) => fireEvent.change(screen.getByLabelText(label), { target: { value } })
function deferred<T>() { let resolve!: (value: T) => void; const promise = new Promise<T>(done => { resolve = done }); return { promise, resolve } }
function Gate({ children }: { children: React.ReactNode }) { return useAuth().status === 'authenticated' ? <>{children}</> : <p>세션 대기</p> }
function mount(path = '/accounting/journals', child: React.ReactNode = <Journals />) {
    const cache = new QueryClient({ defaultOptions: { queries: { retry: false, staleTime: 30_000, gcTime: Infinity, refetchOnWindowFocus: false } } }); clients.push(cache)
    return { ...render(<QueryClientProvider client={cache}><MemoryRouter initialEntries={[path]}><AuthProvider><Gate>{child}</Gate></AuthProvider></MemoryRouter></QueryClientProvider>), cache }
}
async function select(company = a) { await screen.findByLabelText('전표 회사'); change('전표 회사', company); await screen.findByRole('heading', { name: '전표 초안 목록' }); await waitFor(() => expect((button('새 전표 초안') as HTMLButtonElement).disabled).toBe(false)) }
async function createForm() { fireEvent.click(button('새 전표 초안')); await screen.findByLabelText('전표 적요'); await waitFor(() => expect((screen.getByLabelText('1행 계정') as HTMLSelectElement).disabled).toBe(false)); change('회계연도', fy); change('회계일자', '2026-10-07'); change('전표 적요', ' 새 적요 '); change('1행 계정', aa); change('2행 계정', ab); change('1행 차변', '9007199254740993'); change('2행 대변', '9007199254740993') }
async function detail() { fireEvent.click(button('2026-20 · 저장 초안 상세')); await screen.findByRole('heading', { name: '2026-20 · 초안 상세' }) }

beforeEach(() => {
    calls = []; data = [row()]; role = 'COMPANY_ADMIN'; noCompanies = false; next = false; clients = []; override = undefined
    localStorage.clear(); sessionStorage.clear()
    vi.stubGlobal('requestAnimationFrame', (fn: FrameRequestCallback) => setTimeout(() => fn(0), 0))
    vi.stubGlobal('fetch', vi.fn(async (path: string, init: RequestInit = {}) => {
        const c: Call = { url: new URL(path, 'https://example.invalid'), method: init.method ?? 'GET', init, body: init.body ? JSON.parse(String(init.body)) : {} }; calls.push(c)
        const custom = override?.(c); if (custom !== undefined) return await custom
        const p = c.url.pathname
        if (p === '/api/auth/session') return json({ user: { id: user, email: 'fixture@example.invalid' }, csrfToken: 'test-csrf', idleExpiresAt: '2099-01-01', absoluteExpiresAt: '2099-01-01' })
        if (p === '/api/companies') return json({ items: noCompanies ? [] : companies, nextCursor: null })
        if (p.endsWith('/select')) return json({ company: companies.find(x => p.includes(x.id)), roles: [role], permissions: ['journal.read', 'accounts.read', 'counterparties.read', 'evidence.read', ...(['COMPANY_ADMIN', 'ACCOUNTANT', 'EXTERNAL_TAX'].includes(role) ? ['journal.draft'] : [])] })
        if (p.endsWith('/fiscal-years')) return json({ items: years, nextCursor: null })
        if (p.endsWith('/accounts')) return json({ items: accounts, nextCursor: null })
        if (p.endsWith('/counterparties')) return json({ items: [], nextCursor: null })
        if (p.endsWith('/evidence')) return json({ items: [evidence], nextCursor: null })
        if (p.endsWith(`/evidence/${ea}`)) return json({ evidence })
        if (p.endsWith(`/accounts/${aa}`)) return json(accounts[0])
        if (p.endsWith(`/accounts/${ab}`)) return json(accounts[1])
        if (p.endsWith('/journals') && c.method === 'GET') return json({ items: p.includes('/evidence/') ? data.filter(r => r.evidenceIds.includes(ea)) : c.url.searchParams.has('cursor') ? [row(21)] : data.filter(r => !c.url.searchParams.get('q') || r.memo.includes(c.url.searchParams.get('q')!)), nextCursor: next && !c.url.searchParams.has('cursor') ? id(20) : null })
        if (p.endsWith('/journals') && c.method === 'POST') { const saved = { ...row(90), ...c.body, version: 1 }; data.push(saved); return json(saved) }
        // [F05 A2] 기존 초안 시험의 상세 조회도 현재 서버 허용 작업 계약을 반환한다.
        if (p.endsWith('/workflow') && c.method === 'GET') { const current = data.find(r => p.includes(r.id)) ?? row(21); return json({ journal: current, allowedActions: current.status === 'DRAFT' && ['COMPANY_ADMIN', 'ACCOUNTANT'].includes(role) ? ['SUBMIT'] : [], history: { items: [], nextCursor: null } }) }
        if (p.endsWith('/submit') && c.method === 'POST') { const current = data.find(r => p.includes(r.id))!; Object.assign(current, { status: 'SUBMITTED', version: current.version + 1 }); return json({ id: id(80), status: current.status, version: current.version }) }
        if (p.includes('/journals/') && c.method === 'PATCH') { const saved = { ...data[0], ...c.body, version: data[0].version + 1, evidenceCount: c.body.evidenceIds.length }; data[0] = saved; return json(saved) }
        if (p.includes('/journals/') && c.method === 'GET') return json(data.find(r => p.endsWith(r.id)) ?? row(21))
        return error(404)
    }))
})
afterEach(() => { cleanup(); clients.forEach(c => c.clear()); vi.unstubAllGlobals(); vi.restoreAllMocks() })

describe('K3 exact money and body', () => {
    it.each(['0', '-0', '1', '9007199254740993', '999999999999999999'])('accepts canonical integer %s without Number loss', amount => expect(won(amount).toString()).toBe(amount === '-0' ? '0' : amount))
    it.each(['', ' 1', '1 ', '01', '+1', '-1', '1.0', '1e3', '1,000', '1000000000000000000', 'NaN', '-00'])('rejects original syntax %s', amount => expect(() => won(amount)).toThrow())
    it('sums above safe integer exactly and exposes overflow without rounding', () => { expect(journalTotals([{ debit: '9007199254740993', credit: '1' }])).toEqual({ debit: '9007199254740993', credit: '1', difference: '9007199254740992', overflow: false }); expect(journalTotals([{ debit: '999999999999999999', credit: '0' }, { debit: '1', credit: '0' }])?.overflow).toBe(true); expect(journalTotals([{ debit: '1e3', credit: '0' }])).toBeNull() })
    it('normalizes full explicit null/arrays and excludes metadata', () => { const v = valid(); v.evidenceIds = []; v.lines[0].credit = '-0'; const result = normalizeJournalDraft(v, years); expect(result).toMatchObject({ fiscalYearId: fy, content: { memo: '새 적요', counterpartyId: null, evidenceIds: [], lines: [{ accountId: aa, debit: '9007199254740993', credit: '0', memo: null }, { accountId: ab, debit: '0', credit: '9007199254740993', memo: null }] } }); expect(JSON.stringify(result)).not.toContain('createdById') })
    it.each([1, 101])('rejects %i rows', count => { const v = valid(); v.lines = Array.from({ length: count }, () => v.lines[0]); expect(normalizeJournalDraft(v, years).errors.length).toBeGreaterThan(0) })
    it('accepts100 ordered rows and20 distinct references', () => { const v = valid(); v.lines = Array.from({ length: 100 }, (_, i) => ({ accountId: i % 2 ? ab : aa, debit: i % 2 ? '0' : '1', credit: i % 2 ? '1' : '0', memo: String(i) })); v.evidenceIds = Array.from({ length: 20 }, (_, i) => id(100 + i)); expect(normalizeJournalDraft(v, years).errors).toEqual([]) })
    it.each(['zero', 'both', 'unbalanced', 'overflow', 'period', 'year', 'duplicate', '21evidence', 'memo', 'nullchar', 'surrogate'])('rejects %s rule', failure => { const v = valid(); if (failure === 'zero') v.lines.forEach(l => { l.debit = '0'; l.credit = '0' }); if (failure === 'both') v.lines[0].credit = '1'; if (failure === 'unbalanced') v.lines[1].credit = '1'; if (failure === 'overflow') v.lines = [...v.lines, ...v.lines].map(l => ({ ...l, debit: l.debit === '0' ? '0' : '999999999999999999', credit: l.credit === '0' ? '0' : '999999999999999999' })); if (failure === 'period') v.accountingDate = '2027-01-01'; if (failure === 'year') v.fiscalYearId = id(999); if (failure === 'duplicate') v.evidenceIds = [ea, ea]; if (failure === '21evidence') v.evidenceIds = Array.from({ length: 21 }, (_, i) => id(100 + i)); if (failure === 'memo') v.memo = '😀'.repeat(501); if (failure === 'nullchar') v.memo = 'a\0b'; if (failure === 'surrogate') v.lines[0].memo = '\ud800'; expect(normalizeJournalDraft(v, years).errors.length).toBeGreaterThan(0) })
    it('counts Unicode codepoints and validates calendar days', () => { expect(validText('😀'.repeat(500), 500)).toBe(true); expect(validDate('2026-02-29')).toBe(false); expect(validDate('2024-02-29')).toBe(true) })
})
describe('K1 explicit company and current role', () => {
    it('does not select a company/year automatically', async () => { mount(); await screen.findByLabelText('전표 회사'); expect((screen.getByLabelText('전표 회사') as HTMLSelectElement).value).toBe(''); expect(listCalls()).toHaveLength(0) })
    it.each(['COMPANY_ADMIN', 'ACCOUNTANT', 'APPROVER', 'READ_ONLY', 'EXTERNAL_TAX'] as CompanyRole[])('uses actual permission for %s', async value => { role = value; mount(); await screen.findByLabelText('전표 회사'); change('전표 회사', a); await screen.findByRole('heading', { name: '전표 초안 목록' }); await waitFor(() => expect(screen.queryByText('회사 권한 확인 중')).toBeNull()); expect(Boolean(screen.queryByRole('button', { name: '새 전표 초안' }))).toBe(['COMPANY_ADMIN', 'ACCOUNTANT', 'EXTERNAL_TAX'].includes(value)); expect(writes()).toHaveLength(0) })
    it('shows no membership distinctly', async () => { noCompanies = true; mount(); await screen.findByRole('heading', { name: '접근 가능한 회사가 없습니다' }); expect(listCalls()).toHaveLength(0) })
    it('rechecks valid deep link and rejects invalid UUID before select', async () => { mount('/accounting/journals?companyId=no&journalId=no'); await screen.findByText('올바른 회사/전표 초안 링크를 확인해 주세요.'); expect(calls.some(c => c.url.pathname.endsWith('/select'))).toBe(false) })
    it('opens valid linked company/detail after permission check', async () => { mount(`/accounting/journals?companyId=${a}&journalId=${id(20)}`); await screen.findByRole('heading', { name: '2026-20 · 초안 상세' }); expect(calls.some(c => c.url.pathname.endsWith('/select'))).toBe(true) })
    it('ignores delayed former-company reads and removes its cache', async () => { const pending = deferred<Response>(); override = c => c.url.pathname === `/api/companies/${a}/journals` ? pending.promise : undefined; const view = mount(); await select(); change('전표 회사', b); await waitFor(() => expect((screen.getByLabelText('전표 회사') as HTMLSelectElement).value).toBe(b)); await act(async () => pending.resolve(json({ items: [{ ...row(), memo: 'former company' }], nextCursor: null }))); expect(screen.queryByText(/former company/)).toBeNull(); expect(view.cache.getQueriesData({ queryKey: ['journals', user, a] })).toHaveLength(0) })
})
describe('K2 queries and immutable identity', () => {
    it('submits only when the server allows it and refreshes the current detail', async () => { mount(); await select(); await detail(); fireEvent.click(await screen.findByRole('button', { name: '승인 요청', exact: true })); await screen.findByRole('heading', { name: '2026-20 · 승인 요청 상세' }); expect(calls.filter(c => c.url.pathname.endsWith('/submit'))).toHaveLength(1); expect(calls.find(c => c.url.pathname.endsWith('/submit'))?.body).toMatchObject({ version: 1, actionRequestId: expect.any(String) }); expect(screen.getByRole('link', { name: '승인 상태와 이력 보기' }).getAttribute('href')).toBe(`/accounting/approvals?companyId=${a}&journalId=${id(20)}`) })
    it.each([['SUBMITTED', '승인 요청'], ['APPROVED', '승인 완료'], ['REJECTED', '반려']] as const)('F05 W7 keeps %s detail read only', async (status, label) => {
        data = [{ ...row(), status }]; mount(); await select(); fireEvent.click(button('2026-20 · 저장 초안 상세'))
        await screen.findByRole('heading', { name: `2026-20 · ${label} 상세` })
        expect(screen.queryByRole('button', { name: '초안 수정' })).toBeNull()
        expect(writes()).toHaveLength(0)
    })
    it('sends inclusive filters/20/cursor and restores previous page', async () => { next = true; mount(); await select(); change('번호·적요 검색', ' 저장 '); change('회계연도 필터', fy); change('회계일자 시작', '2026-01-01'); change('회계일자 종료', '2026-12-31'); fireEvent.click(button('전표 검색')); await waitFor(() => expect(listCalls().at(-1)!.url.searchParams.get('q')).toBe('저장')); expect(Object.fromEntries(listCalls().at(-1)!.url.searchParams)).toEqual({ limit: '20', q: '저장', fiscalYearId: fy, from: '2026-01-01', to: '2026-12-31' }); await waitFor(() => expect((button('다음 페이지') as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(button('다음 페이지')); await waitFor(() => expect(listCalls().at(-1)!.url.searchParams.get('cursor')).toBe(id(20))); await waitFor(() => expect((button('이전 페이지') as HTMLButtonElement).disabled).toBe(false)); fireEvent.click(button('이전 페이지')); await screen.findByText('1페이지') })
    it('rejects backwards dates without request', async () => { mount(); await select(); change('회계일자 시작', '2026-12-01'); change('회계일자 종료', '2026-01-01'); const count = listCalls().length; fireEvent.click(button('전표 검색')); await screen.findByRole('alert'); expect(listCalls()).toHaveLength(count) })
    it('retains number/year/creator and sends version/full content without identity', async () => { mount(); await select(); await detail(); fireEvent.click(button('초안 수정')); expect((screen.getByLabelText('회계연도') as HTMLInputElement).readOnly).toBe(true); change('전표 적요', '변경 적요'); fireEvent.click(button('초안 변경 저장')); await waitFor(() => expect(writes()).toHaveLength(1)); expect(writes()[0].body).toEqual({ version: 1, accountingDate: '2026-10-07', memo: '변경 적요', counterpartyId: null, evidenceIds: [ea], lines: row().lines.map(({ accountId, debit, credit, memo }) => ({ accountId, debit, credit, memo })) }); expect(data[0].number).toBe(row().number); expect(data[0].createdById).toBe(user) })
    it('forwards fiscal year cursor without changing existing signal argument', async () => { const c = new AbortController(); await companyApi.fiscalYears(a, c.signal, fy); expect(calls[0].url.searchParams.get('cursor')).toBe(fy); expect(calls[0].init.signal).toBe(c.signal) })
})
describe('K4 fixed request and conflict', () => {
    it('locks navigation and double submit immediately with canonical body/CSRF', async () => { const pending = deferred<Response>(); override = c => c.method === 'POST' && c.url.pathname.endsWith('/journals') ? pending.promise : undefined; mount(); await select(); await createForm(); const submit = button('초안 저장'); fireEvent.click(submit); fireEvent.click(submit); await waitFor(() => expect(writes()).toHaveLength(1)); expect((screen.getByLabelText('전표 회사') as HTMLSelectElement).disabled).toBe(true); expect(writes()[0].body).toMatchObject({ fiscalYearId: fy, memo: '새 적요', counterpartyId: null, evidenceIds: [] }); expect(writes()[0].body.creationRequestId).toMatch(/^[0-9a-f-]{36}$/); expect(writes()[0].init.credentials).toBe('include'); expect(writes()[0].init.headers).toMatchObject({ 'X-CSRF-Token': 'test-csrf' }); await act(async () => pending.resolve(json(row(90)))); await screen.findByRole('heading', { name: '2026-90 · 초안 상세' }) })
    it.each(['network', '503'])('retries %s only with same frozen request', async failure => { let n = 0; override = c => c.method === 'POST' && c.url.pathname.endsWith('/journals') && n++ === 0 ? failure === 'network' ? Promise.reject(new TypeError('offline')) : error(503) : undefined; mount(); await select(); await createForm(); fireEvent.click(button('초안 저장')); await screen.findByRole('button', { name: '같은 요청으로 다시 확인' }); expect((screen.getByLabelText('전표 적요') as HTMLInputElement).disabled).toBe(true); expect(writes()).toHaveLength(1); fireEvent.click(button('같은 요청으로 다시 확인')); await screen.findByRole('heading', { name: '2026-90 · 초안 상세' }); expect(writes()).toHaveLength(2); expect(writes()[1].body).toEqual(writes()[0].body); expect(localStorage.length + sessionStorage.length).toBe(0) })
    it.each([409, 503, 'network'] as const)('preserves old edit for %s until explicit latest/discard with no automatic overwrite', async status => { override = c => c.method === 'PATCH' ? status === 'network' ? Promise.reject(new TypeError('offline')) : error(status) : undefined; mount(); await select(); await detail(); fireEvent.click(button('초안 수정')); change('전표 적요', '미저장 초안'); fireEvent.click(button('초안 변경 저장')); await screen.findByRole('button', { name: '현재 저장 상태 확인' }); expect((screen.getByLabelText('전표 적요') as HTMLInputElement).value).toBe('미저장 초안'); expect((button('기존 입력 폐기하고 다시 수정') as HTMLButtonElement).disabled).toBe(true); expect(writes()).toHaveLength(1); data[0] = { ...data[0], version: 2, memo: '다른 사용자 변경' }; fireEvent.click(button('현재 저장 상태 확인')); await waitFor(() => expect((button('기존 입력 폐기하고 다시 수정') as HTMLButtonElement).disabled).toBe(false)); expect((screen.getByLabelText('전표 적요') as HTMLInputElement).value).toBe('미저장 초안'); fireEvent.click(button('기존 입력 폐기하고 다시 수정')); fireEvent.click(button('입력 폐기 확인')); await waitFor(() => expect((screen.getByLabelText('전표 적요') as HTMLInputElement).value).toBe('다른 사용자 변경')); expect(writes()).toHaveLength(1) })
    it('requires inline discard for company change of dirty input', async () => { mount(); await select(); await createForm(); change('전표 회사', b); expect((screen.getByLabelText('전표 회사') as HTMLSelectElement).value).toBe(a); fireEvent.click(button('입력 유지')); expect(screen.getByLabelText('전표 적요')).toBeTruthy(); change('전표 회사', b); fireEvent.click(button('입력 폐기 확인')); await waitFor(() => expect((screen.getByLabelText('전표 회사') as HTMLSelectElement).value).toBe(b)); expect(writes()).toHaveLength(0) })
    it('uses server no-op version without inventing an increase', async () => { override = c => c.method === 'PATCH' ? json(row()) : undefined; mount(); await select(); await detail(); fireEvent.click(button('초안 수정')); fireEvent.click(button('초안 변경 저장')); await screen.findByText('전표 초안의 현재 저장 상태를 확인했습니다.'); expect(data[0].version).toBe(1); expect(writes()).toHaveLength(1) })
})
describe('K5 evidence and reference behavior', () => {
    it('unlinks through whole PATCH only and keeps original metadata', async () => { mount(); await select(); await detail(); fireEvent.click(button('초안 수정')); await screen.findByRole('button', { name: '시험 PDF · test.pdf 연결 해제' }); fireEvent.click(button('시험 PDF · test.pdf 연결 해제')); fireEvent.click(button('초안 변경 저장')); await waitFor(() => expect(writes()).toHaveLength(1)); expect(writes()[0].body.evidenceIds).toEqual([]); expect(writes()[0].method).toBe('PATCH'); expect(evidence.originalFileName).toBe('test.pdf'); expect(calls.filter(c => c.url.pathname.includes('/evidence') && c.method !== 'GET')).toHaveLength(0) })
    it('shows two reverse links without independent write and preserves preview controls', async () => { data.push(row(21)); mount('/accounting/evidence', <EvidenceDetail evidence={evidence} companyId={a} userId={user} canReadJournals onUnauthorized={vi.fn()} onForbidden={vi.fn()} isCurrent={() => true} />); await screen.findByRole('link', { name: '2026-20 초안 열기' }); expect(screen.getByRole('link', { name: '2026-21 초안 열기' }).getAttribute('href')).toBe(`/accounting/journals?companyId=${a}&journalId=${id(21)}`); expect(button('원본 미리보기')).toBeTruthy(); expect(button('원본 다운로드')).toBeTruthy(); expect(writes()).toHaveLength(0) })
    it('does not reverse-query without journal permission', async () => { mount('/accounting/evidence', <EvidenceDetail evidence={evidence} companyId={a} onUnauthorized={vi.fn()} onForbidden={vi.fn()} isCurrent={() => true} />); await screen.findByRole('heading', { name: '증빙 상세' }); expect(calls.some(c => c.url.pathname.endsWith('/journals'))).toBe(false) })
    it('opens linked evidence with reselected company and reverse permission', async () => { mount(`/accounting/evidence?companyId=${a}&evidenceId=${ea}`, <Evidence />); await screen.findByRole('heading', { name: '증빙 상세' }); await screen.findByRole('link', { name: '2026-20 초안 열기' }); expect(calls.some(c => c.url.pathname.endsWith('/select'))).toBe(true) })
    it('keeps unavailable old reference ID visible instead of hiding it', async () => { override = c => c.url.pathname.endsWith(`/accounts/${aa}`) ? error(404) : undefined; mount('/', <JournalReferencePicker kind="account" companyId={a} userId={user} id="old" label="기존 계정" selected={[aa]} readOnly onAccessError={vi.fn()} />); await screen.findByText(`${aa} · 현재 이름 확인 불가 · 현재 사용 자격 확인 필요`) })
})
describe('K6 states and keyboard error focus', () => {
    it('gives selection guidance without exposing UUID implementation errors', () => { const result = normalizeJournalDraft(draftValues(), years); expect(result.errors.map(e => e.message).join('\n')).not.toContain('UUID'); expect(result.errors.some(e => e.message === '올바른 항목을 선택해 주세요.')).toBe(true) })
    it('focuses linked validation summary and leaves initial account/year/date blank', async () => { mount(); await select(); fireEvent.click(button('새 전표 초안')); expect((screen.getByLabelText('회계연도') as HTMLSelectElement).value).toBe(''); expect((screen.getByLabelText('회계일자') as HTMLInputElement).value).toBe(''); expect((screen.getByLabelText('1행 계정') as HTMLSelectElement).value).toBe(''); fireEvent.click(button('초안 저장')); await waitFor(() => expect(document.activeElement).toBe(screen.getByRole('alert'))); expect(screen.getByRole('link', { name: '적요는 올바른 문자로1~500자에 입력해 주세요.' }).getAttribute('href')).toBe('#j-memo'); expect(writes()).toHaveLength(0) })
    it.each([400, 404, 409, 429, 503, 'network'] as const)('shows failed read %s with manual retry instead of empty-success', async status => { override = c => c.url.pathname === `/api/companies/${a}/journals` ? status === 'network' ? Promise.reject(new TypeError('offline')) : error(status) : undefined; mount(); await select(); await screen.findByRole('heading', { name: '전표 목록을 불러오지 못했습니다' }); expect(listCalls()).toHaveLength(1); expect(screen.queryByText(/private internal/)).toBeNull(); fireEvent.click(button('다시 시도')); await waitFor(() => expect(listCalls()).toHaveLength(2)) })
    it('expires401 through real auth provider and clears cache', async () => { override = c => c.url.pathname === `/api/companies/${a}/journals` ? error(401) : undefined; const view = mount(); await screen.findByLabelText('전표 회사'); change('전표 회사', a); await screen.findByText('세션 대기'); expect(view.cache.getQueryCache().getAll()).toHaveLength(0) })
    it('rechecks403 and clears company after lost membership', async () => { let n = 0; override = c => c.url.pathname.endsWith('/select') && ++n > 1 ? error(403) : c.url.pathname === `/api/companies/${a}/journals` ? error(403) : undefined; const view = mount(); await screen.findByLabelText('전표 회사'); change('전표 회사', a); await screen.findByText('회사 접근 권한을 확인하지 못했습니다. 회사를 다시 선택해 주세요.'); expect((screen.getByLabelText('전표 회사') as HTMLSelectElement).value).toBe(''); expect(view.cache.getQueriesData({ queryKey: ['journals', user, a] })).toHaveLength(0) })
    it('removes draft after write403 and refreshed read-only permissions', async () => { override = c => { if (c.method === 'POST' && c.url.pathname.endsWith('/journals')) { role = 'READ_ONLY'; return error(403) } }; mount(); await select(); await createForm(); fireEvent.click(button('초안 저장')); await screen.findByText('현재 회사 권한을 다시 확인했습니다. 입력은 새로 시작해 주세요.'); expect(screen.queryByLabelText('전표 적요')).toBeNull(); expect(screen.queryByRole('button', { name: '새 전표 초안' })).toBeNull() })
    it('aborts active read on unmount and ignores a late write result', async () => { const pending = deferred<Response>(); override = c => c.method === 'POST' && c.url.pathname.endsWith('/journals') ? pending.promise : undefined; const view = mount(); await select(); await createForm(); fireEvent.click(button('초안 저장')); await waitFor(() => expect(writes()).toHaveLength(1)); view.unmount(); await act(async () => pending.resolve(json(row(90)))); expect(view.cache.getQueryData(['journal', user, a, id(90)])).toBeUndefined() })
    it('GET APIs propagate AbortSignal with no CSRF/write', async () => { const controller = new AbortController(); await journalApi.list(a, {}, undefined, controller.signal); await journalApi.detail(a, id(20), controller.signal); await journalApi.forEvidence(a, ea, id(20), controller.signal); expect(calls.every(c => c.method === 'GET' && c.init.signal === controller.signal)).toBe(true); expect(calls[0].init.headers).not.toHaveProperty('X-CSRF-Token') })
})
